# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-11 20:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acesso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissao_acesso', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_pessoa', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200, null=True)),
                ('codigo_cartao', models.CharField(max_length=30)),
                ('cpf', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Porta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_porta', models.IntegerField(default=0)),
                ('descricao_porta', models.CharField(max_length=200)),
                ('codigo_porta', models.CharField(max_length=10)),
                ('ip', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_acesso', models.DateTimeField(default=django.utils.timezone.now)),
                ('codigo_recebido', models.CharField(max_length=30)),
                ('permissao', models.BooleanField(default=False)),
                ('acesso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='unlock.Acesso')),
                ('pessoa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='unlock.Pessoas')),
                ('porta_acessada', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='unlock.Porta')),
            ],
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_setor', models.CharField(max_length=30)),
                ('outro_nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='porta',
            name='setor_porta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='unlock.Setor'),
        ),
        migrations.AddField(
            model_name='pessoas',
            name='setor_pessoa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='unlock.Setor'),
        ),
        migrations.AddField(
            model_name='acesso',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unlock.Pessoas'),
        ),
        migrations.AddField(
            model_name='acesso',
            name='porta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unlock.Porta'),
        ),
    ]
