# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-11 20:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('unlock', '0002_setor_teste_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setor',
            name='outro_nome',
        ),
        migrations.RemoveField(
            model_name='setor',
            name='teste_nome',
        ),
        migrations.AddField(
            model_name='setor',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
