# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-26 22:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('unlock', '0004_auto_20180411_2354'),
    ]

    operations = [
        migrations.CreateModel(
            name='Botao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_botao', models.CharField(max_length=100)),
                ('endereco_botao', models.CharField(max_length=300)),
                ('cep', models.CharField(max_length=9)),
                ('email_botao', models.CharField(max_length=200, null=True)),
                ('telefone_botao', models.CharField(max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Registrobotao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_acesso', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Situacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_botao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unlock.Botao')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_status', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='situacao',
            name='nome_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unlock.Status'),
        ),
        migrations.AddField(
            model_name='registrobotao',
            name='situacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unlock.Situacao'),
        ),
    ]
