# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-27 13:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unlock', '0005_auto_20180726_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='situacao',
            name='nome_botao',
        ),
        migrations.RemoveField(
            model_name='situacao',
            name='nome_status',
        ),
        migrations.RemoveField(
            model_name='registrobotao',
            name='situacao',
        ),
        migrations.AddField(
            model_name='botao',
            name='situacao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='unlock.Status'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrobotao',
            name='nome_botao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='unlock.Botao'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Situacao',
        ),
    ]
