# Generated by Django 2.0.8 on 2018-12-07 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlock', '0008_botao_key_botao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lampada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lampada', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
